# -*- coding: utf-8 -*-
"""after_xl_scr
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1b3VXkHSUL8qaZE8LvrnmW17Nh3gh3TGN
"""

from openpyxl import load_workbook
import streamlit as st
from io import BytesIO
import requests
import shutil

# コメントアウトされたコード

def xl_data_upload(uploaded_file):
    str_data = []
    
    #after_xl = st.file_uploader("アフター申請書エクセルをアップロードしてください")

    if uploaded_file is not None:
        file_mime = uploaded_file.type
        if file_mime == 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
            try:
                file = BytesIO(uploaded_file.getvalue())
                wb = load_workbook(filename=file)
                sheet = wb.active
                rects = ["G19","G20","L15","N20","G21","N21","G23","Q23","H28","AB34"]

                for rect in rects:
                    str_data.append(sheet[rect].value)

                for rect, value in zip(rects, str_data):
                    st.write(f"{rect}: {value}")
                
                return str_data

            except Exception as e:
                st.error(f"エラーが発生しました: {e}")
                return None

        else:
            st.write("エクセルファイル(.xlsx)をアップロードしてください")
            st.stop()
            

def main (uploaded_file):
    """
    GitHubからExcelファイルをダウンロードし、開く関数。
    """
    str_data = ""
    xlpoints = ["AC9-1","AC9","AM9","AC11","AC13","AC15","AC19-1","AC19","A11","S11"]
    
    #after_xl = st.file_uploader("アフター申請書エクセルをアップロードしてください")
    
    if uploaded_file is not None:
        str_data = xl_data_upload(uploaded_file)
    
    else:
        st.write("エクセルファイル(.xlsx)をアップロードしてください")
        st.stop()

    genba = "現場名："
    syukka = st.date_input("出荷日を入力してください")
    konpou = st.selectbox("梱包数を選択してください",['1','2','3','4','5','それ以上'])
    if konpou =='それ以上':
        konpou = st.text_input('梱包数を入力してください(半角数字)')
        
    if st.button("Excelファイルを生成する"):
        github_url = "https://github.com/shintarotakasaki/excel3/raw/main/伝票(規格品)_ラベル_指示書.xlsm"
        # ファイルをダウンロードして一時ファイルとして保存
        response = requests.get(github_url,stream=True)
        if response.status_code == 200:
            file_path = "伝票(規格品)_ラベル_指示書.xlsm"  # ここで file_path を定義
            with open("伝票(規格品)_ラベル_指示書.xlsm",'wb')as f:
                response.raw.decode_content = True
                shutil.copyfileobj(response.raw, f)
            
        try:
            wb_demp = load_workbook(file_path, keep_vba=True)
            ws_demp = wb_demp['納品書控(製品)']
            wb_demp.active = ws_demp
        except Exception as e:
            st.error(f"エラーが発生しました: {e}")

